#include <stdio.h>
#include <unistd.h>
#include <sys/resource.h>
#include <bpf/libbpf.h>
#include "traceproc.skel.h" // This is to be generated by bpftool during build

static int libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args)
{
    return vfprintf(stderr, format, args);
}

int main(int argc, char **argv)
{
    struct traceproc_bpf *skel;
    int err;

    libbpf_set_strict_mode(LIBBPF_STRICT_ALL);
    libbpf_set_print(libbpf_print_fn);

    skel = traceproc_bpf__open();
    if (!skel) {
        fprintf(stderr, "Failed to open BPF skeleton.\n");
        return 1;
    }

    err = traceproc_bpf__load(skel);
    if (err) {
        fprintf(stderr, "Failed to attach to BPF skeleton.\n");
        goto cleanup;
    }

    err = traceproc_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "Failed to attach to BPF skeleton.\n");
        goto cleanup;
    }

    printf("Started! Run `sudo cat /sys/kernel/debug/tracing/trace_pipe` to see output.\n");

    sleep(30);

cleanup:
    traceproc_bpf__destroy(skel);
    return -err;
}